### PR TITLE
Deploy only on main branch

### PR DESCRIPTION
**Pull request by clementbiron**

### CODE REVIEW

**Comment by MattiSG** [comment]
I am surprised that this necessary feature is implemented with a conditional at the very last step. I believe the root cause of the unexpected behaviour is that this workflow is triggered for any `pull_request`. Have you tried simply ensuring that this workflow is triggered only by pushes on `main`? 🙂

**Comment by martinratinaud** [comment]
@clementbiron you can do so by using this

```
name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  test:
    ...
```

**Comment by clementbiron** [comment]
> @clementbiron you can do so by using this
> 
> ```
> name: Deploy
> 
> on:
>   push:
>     branches: [ main ]
> 
> jobs:
>   test:
>     ...
> ```

This seems to me to be the way it is implemented, no?

```
on:
  push:
    branches:
      - main  # Set a branch that will trigger a deployment
  pull_request:
 ```

**Comment by clementbiron** [comment]
OK thank you both, I understand better.

I [opened a PR](https://github.com/OpenTermsArchive/docs/pull/29/files) to stop deploying on each pull request and remove unecessary condition.

**Pull request merged**
